---
- hosts: localhost # pulling a repo down to run on a localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - cowsay
        - tmux
        - vim
        - git
        - rclone
        - rsync
