---
- hosts: localhost # pulling a repo down to run on a localhost
  connection: local
  become: true
  vars:
    home: "/home/oscqr/"
    # home: "{{ lookup( 'ansible.builtin.env', 'HOME')  }}"

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - cowsay
        - tmux
        - vim
        - git
        - rclone
        - rsync
        - zsh
        - rsync
        - rclone
        - tree
        - neovim
        - fzf
        - terminator
        - stow
