---
- hosts: localhost # pulling a repo down to run on a localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - cowsay
        - tmux
        - vim
        - git
        - rclone
        - rsync
        - zsh
        - rsync
        - rclone
        - tree

  - name: Clone the configs
    git:
      repo: git@github.com:Makcime/configs.git
      dest: "{{ lookup( 'ansible.builtin.env', 'HOME')  }}"
      key_file: ~.ssh/id_ed25519
      clone: yes
      update: yes
